# Espanso configuration file for greek letters

name: greek-letters-full
parent: default



matches:

    ## Shorthand ∨ Name ⇒ :Symbol:
    # :gA: ∨ :Alpha: ⇒ A
    - triggers: [":gA:", ":Alpha:"]
      replace: "Α"
      
    # :ga: ∨ :alpha: ⇒ α
    - triggers: [":ga:", ":alpha:"]
      replace: "α"

    # :gB: ∨ :Beta: ⇒ Β
    - triggers: [":gB:", ":Beta:"]
      replace: "Β"
    
    # :gb: ∨ :beta: ⇒ β
    - triggers: [":gb:", ":beta:"]
      replace: "β"

    # :gD: ∨ :Delta: ⇒ Δ
    - triggers: [":gD:", ":Delta:"]
      replace: "Δ"

    # :gd: ∨ :delta: ⇒ δ
    - triggers: [":gd:", ":delta:"]
      replace: "δ"
      
    # :gE: ∨ :Epsilon: ⇒ Ε
    - triggers: [":gE:", ":Epsilon:"]
      replace: "Ε"
      
    # :ge: ∨ :epsilon: ⇒ ε
    - triggers: [":ge:", ":epsilon:"]
      replace: "ε"
      
    # :gF: ∨ :Phi: ⇒ Φ
    - triggers: [":gF:", ":Phi:"]
      replace: "Φ"
    
    # :gf: ∨ :phi: ⇒ φ
    - triggers: [":gf:", ":phi:"]
      replace: "φ"
    
    # :gG: ∨ :Gamma: ⇒ Γ
    - triggers: [":gG:", ":Gamma:"]
      replace: "Γ"
      
    # :gg: ∨ :gamma: ⇒ γ
    - triggers: [":gg:", ":gamma:"]
      replace: "γ"
      
    # :gH: ∨ :Eta: ⇒ Η
    - triggers: [":gH:", ":Eta:"]
      replace: "Η"
    
    # :gh: ∨ η ⇒ η
    - triggers: [":gh:", ":eta:"]
      replace: "η"
      
    # :gI: ∨ :Iota: ⇒ Ι
    - triggers: [":gI:", ":Iota:"]
      replace: "Ι"
    
    # :gi: ∨ :iota: ⇒ ι
    - triggers: [":gi:", ":iota:"]
      replace: "ι"
      
    # :gJ: ∨ :Theta: ⇒ Θ
    - triggers: [":gJ:", ":Theta:"]
      replace: "Θ"
    
    # :gj: :theta: ⇒ θ
    - triggers: [":gj:", ":theta:"]
      replace: "θ"

    # :gK: ∨ :Kappa: ⇒ Κ
    - triggers: [":gK:", ":Kappa:"]
      replace: "Κ"
      
    # :gk: ∨ :kappa: ⇒ κ
    - triggers: [":gk:", ":kappa:"]
      replace: "κ"
      
    # :gL:∨ :Lambda: ⇒ Λ
    - triggers: [":gL:", ":Lambda:"]
      replace: "Λ"
      
    # :gl: ∨ :lambda: ⇒ λ
    - triggers: [":gl:", ":lambda:"]
      replace: "λ" 
      
    # :gM: ∨ :Mu: ⇒ Μ
    - triggers: [":gM:", ":Mu:"]
      replace: "Μ"
    
    # :gm: ∨ :mu: ⇒ μ
    - triggers: [":gm:", ":mu:"]
      replace: "μ"
    
    # :gN: ∨ :Nu: ⇒ Ν
    - triggers: [":gN:", ":Nu:"]
      replace: "Ν"
      
    # :gn: ∨ :nu: ⇒ ν
    - triggers: [":gn:", ":nu:"]
      replace: "ν"
    
    # :gO:  ∨ :Omnicron: ⇒ Ο
    - triggers: [":gO:", ":Omnicron:"]
      replace: "Ο"
      
    # :go: ∨ :omnicron: ⇒ ο
    - triggers: [":go:", ":omnicron:"]
      replace: "ο"
      
    # :gP: ∨ :Pi: ⇒ Π
    - triggers: [":gP:", ":Pi:"]
      replace: "Π"
      
    # :gp: ∨ :pi: ⇒ π
    - triggers: [":gp:", ":pi:"]
      replace: "π"
            
    # :gQ: ∨ :Chi: ⇒ Χ
    - triggers: [":gQ:", ":Chi:"]
      replace: "Χ"
      
    # :gq: ∨ :chi: ⇒ χ
    - triggers: [":gq:", ":chi:"]
      replace: "χ"
      
    # :gR: ∨ :Rho: ⇒ Ρ
    - triggers: [":gR:", ":Rho:"]
      replace: "Ρ"
    
    # :gr: ∨ :rho: ⇒ ρ
    - triggers: [":gr:", ":rho:"]
      replace: "ρ"
    
    # :gS: ∨ :Sigma: ⇒ Σ
    - triggers: [":gS:", ":Sigma:"]
      replace: "Σ"
    
    # :gs: ∨ :sigma: ⇒ σ
    - triggers: [":gs:", ":sigma:"]
      replace: "σ"
      
    # :gT: ∨ :Tau: ⇒ Τ
    - triggers: [":gT:", ":Tau:"]
      replace: "Τ"
    
    # :gt: ∨ :tau: ⇒ τ
    - triggers: [":gt:", ":tau:"]
      replace: "τ"
    
    # :gU: ∨ :Upsilon: ⇒ Υ
    - triggers: [":gU:", ":Upsilon:"]
      replace: "Υ"
      
    # :gu: ∨ :upsilon: ⇒ υ
    - triggers: [":gu:", ":upsilon:"]
      replace: "υ"
      
    # :gW: ∨ :Omega: ⇒ Ω
    - triggers: [":gW:", ":Omega:"]
      replace: "Ω"
      
    # :gw: ∨ :omega: ⇒ ω
    - triggers: [":gw:", ":omega:"]
      replace: "ω"
    
    # :gX: ∨ :Xi: ⇒ Ξ
    - triggers: [":gX:", ":Xi:"]
      replace: "Ξ"
      
    # :gx: ∨ :xi: ⇒ ξ
    - triggers: [":gx:", ":xi:"]
      replace: "ξ"
      
    # :gY: ∨ :Psi: ⇒ Ψ
    - triggers: [":gY:", ":Psi:"]
      replace: "Ψ"
      
    # :gy: ∨ :psi: ⇒ ψ
    - triggers: [":gy:", ":psi:"]
      replace: "ψ"

    # :gZ: ∨ :Zeta: ⇒ Ζ
    - triggers: [":gZ:", ":Zeta:"]
      replace: "Ζ"

    # :gz: ∨ :zeta: ⇒ ζ
    - triggers: [":gz:", ":zeta:"]
      replace: "ζ"
