name: enumeration
parent: default

matches:

  # White Background
  - trigger: ':(0)'
    replace: '⓪'
  - trigger: ':(1)'
    replace: '①'
  - trigger: ':(2)'
    replace: '②'
  - trigger: ':(3)'
    replace: '③'
  - trigger: ':(4)'
    replace: '④'
  - trigger: ':(5)'
    replace: '⑤'
  - trigger: ':(6)'
    replace: '⑥'
  - trigger: ':(7)'
    replace: '⑦'
  - trigger: ':(8)'
    replace: '⑧'
  - trigger: ':(9)'
    replace: '⑨'
  - trigger: ':(10)'
    replace: '⑩'
  - trigger: ':(11)'
    replace: '⑪'
  - trigger: ':(12)'
    replace: '⑫'
  - trigger: ':(13)'
    replace: '⑬'
  - trigger: ':(14)'
    replace: '⑭'
  - trigger: ':(15)'
    replace: '⑮'
  - trigger: ':(16)'
    replace: '⑯'
  - trigger: ':(17)'
    replace: '⑰'
  - trigger: ':(18)'
    replace: '⑱'
  - trigger: ':(19)'
    replace: '⑲'
  - trigger: ':(20)'
    replace: '⑳'
  - trigger: ':(21)'
    replace: '㉑'
  - trigger: ':(22)'
    replace: '㉒'
  - trigger: ':(23)'
    replace: '㉓'
  - trigger: ':(24)'
    replace: '㉔'
  - trigger: ':(25)'
    replace: '㉕'
  - trigger: ':(26)'
    replace: '㉖'
  - trigger: ':(27)'
    replace: '㉗'
  - trigger: ':(28)'
    replace: '㉘'
  - trigger: ':(29)'
    replace: '㉙'
  - trigger: ':(30)'
    replace: '㉚'
  - trigger: ':(31)'
    replace: '㉛'
  - trigger: ':(32)'
    replace: '㉜'
  - trigger: ':(33)'
    replace: '㉝'
  - trigger: ':(34)'
    replace: '㉞'
  - trigger: ':(35)'
    replace: '㉟'
  - trigger: ':(36)'
    replace: '㊱'
  - trigger: ':(37)'
    replace: '㊲'
  - trigger: ':(38)'
    replace: '㊳'
  - trigger: ':(39)'
    replace: '㊴'
  - trigger: ':(40)'
    replace: '㊵'
  - trigger: ':(41)'
    replace: '㊶'
  - trigger: ':(42)'
    replace: '㊷'
  - trigger: ':(43)'
    replace: '㊸'
  - trigger: ':(44)'
    replace: '㊹'
  - trigger: ':(45)'
    replace: '㊺'
  - trigger: ':(46)'
    replace: '㊻'
  - trigger: ':(47)'
    replace: '㊼'
  - trigger: ':(48)'
    replace: '㊽'
  - trigger: ';(49)'
    replace: '㊾'
  - trigger: ':(50)'
    replace: '㊿'

  # black background
  - trigger: ':{0}'
    replace: '⓿'
  - trigger: ':{1}'
    replace: '❶'
  - trigger: ':{2}'
    replace: '❷'
  - trigger: ':{3}'
    replace: '❸'
  - trigger: ':{4}'
    replace: '❹'
  - trigger: ':{5}'
    replace: '❺'
  - trigger: ':{6}'
    replace: '❻'
  - trigger: ':{7}'
    replace: '❼'
  - trigger: ':{8}'
    replace: '❽'
  - trigger: ':{9}'
    replace: '❾'
  - trigger: ':{10}'
    replace: '❿'
  - trigger: ':{11}'
    replace: '⓫'
  - trigger: ':{12}'
    replace: '⓬'
  - trigger: ':{13}'
    replace: '⓭'
  - trigger: ':{14}'
    replace: '⓮'
  - trigger: ':{15}'
    replace: '⓯'
  - trigger: ':{16}'
    replace: '⓰'
  - trigger: ':{17}'
    replace: '⓱'
  - trigger: ':{18}'
    replace: '⓲'
  - trigger: ':{19}'
    replace: '⓳'

  - trigger: ':{20}'
    replace: '⓴'
